### PR TITLE
Automating release to winget-pkgs

### PR DESCRIPTION
**Pull request by solomoncyj**
# Do not merege this pr untill the following have been merged
 * https://github.com/microsoft/winget-pkgs/pull/107245
 * https://github.com/microsoft/winget-pkgs/pull/107244
 * https://github.com/microsoft/winget-pkgs/pull/107243

### CODE REVIEW

**Review by vedantmgoyal2009 — CHANGES_REQUESTED** [review]

**Comment by solomoncyj** [comment]
Ready to merge @Vendicated

**Comment by Justman100** [comment]
@Vendicated

**Comment by Justman100** [comment]
@Vendicated

Why closed?

**Comment by Vendicated** [comment]
because this pr was never wanted and this was communicated to the author in our community channels.

simply noone ever bothered closing this pr

**Pull request closed without merging**
